command:
- ${env}
- python
- ${program}
- configs/config_remote.json
method: bayes
metric:
  goal: maximize
  name: overall_f1
parameters:
  batch_size:
    values:
    - 4
    - 8
    - 16
  learning_rate:
    min: 0.000001
    max: 0.001
  num_sentences:
    min: 2
    max: 40
  model_name:
    distribution: categorical
    values:
    - xlm-roberta-base
    - Babelscape/wikineural-multilingual-ner
program: src/finetune_ner.py
